-- KursusKilat seed — generated by tool/generate_seed.dart

-- ─── Courses ───────────────────────────────────────────────────────────────
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('💻', 'PROGRAMMING', 'Dasar Pemrograman', 'Konsep variabel, tipe data, percabangan, perulangan, dan struktur program.', '', 'Materi teori', 4, 4278190232, 4278190111, 1);
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('🧮', 'ILMU KOMPUTER', 'Algoritma & Struktur Data', 'Cara data disusun, dicari, dibandingkan, dan diproses secara efisien.', '', 'Materi teori', 4, 4278190506, 4278190111, 2);
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('📊', 'DATABASE', 'Basis Data', 'Relasi data, kunci, normalisasi, transaksi, dan konsep penyimpanan informasi.', '', 'Materi teori', 4, 4279308362, 4278190111, 3);
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('🌐', 'NETWORKING', 'Jaringan Komputer', 'Protokol, alamat jaringan, model komunikasi, dan keamanan dasar jaringan.', '', 'Materi teori', 4, 4286578701, 4283822093, 4);
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('🤖', 'AI & ML', 'Kecerdasan Buatan', 'Konsep agen cerdas, pembelajaran mesin, data, model, dan evaluasi AI.', '', 'Materi teori', 4, 4279508522, 4279508256, 5);

-- ─── Materials (4 per course) ────────────────────────────────────────────
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (1, 'Istilah Dasar', '📘', 'Ringkas', 'Bagian ini mengenalkan istilah dasar dalam Dasar Pemrograman sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.', '["Definisi konsep utama","Fungsi setiap istilah","Perbedaan istilah yang mirip","Contoh penerapan secara umum"]'::jsonb, 1);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (1, 'Konsep Inti', '🧠', 'Teori', 'Konsep inti menjelaskan prinsip yang membuat Dasar Pemrograman bekerja sebagai sebuah bidang ilmu. Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.', '["Prinsip kerja utama","Masalah yang diselesaikan","Kelebihan dan batasan konsep","Hubungan sebab-akibat"]'::jsonb, 2);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (1, 'Hubungan Antar Konsep', '🔗', 'Analisis', 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.', '["Konsep prasyarat","Konsep pembanding","Dampak perubahan sistem","Pola hubungan dalam soal"]'::jsonb, 3);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (1, 'Pola Soal Kuis', '🎯', 'Kuis', 'Bagian ini merangkum cara konsep Dasar Pemrograman biasanya diubah menjadi pertanyaan pilihan ganda. Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.', '["Soal definisi","Soal perbandingan konsep","Soal studi kasus singkat","Distraktor jawaban yang mirip"]'::jsonb, 4);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (2, 'Istilah Dasar', '📘', 'Ringkas', 'Bagian ini mengenalkan istilah dasar dalam Algoritma & Struktur Data sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.', '["Definisi konsep utama","Fungsi setiap istilah","Perbedaan istilah yang mirip","Contoh penerapan secara umum"]'::jsonb, 1);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (2, 'Konsep Inti', '🧠', 'Teori', 'Konsep inti menjelaskan prinsip yang membuat Algoritma & Struktur Data bekerja sebagai sebuah bidang ilmu. Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.', '["Prinsip kerja utama","Masalah yang diselesaikan","Kelebihan dan batasan konsep","Hubungan sebab-akibat"]'::jsonb, 2);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (2, 'Hubungan Antar Konsep', '🔗', 'Analisis', 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.', '["Konsep prasyarat","Konsep pembanding","Dampak perubahan sistem","Pola hubungan dalam soal"]'::jsonb, 3);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (2, 'Pola Soal Kuis', '🎯', 'Kuis', 'Bagian ini merangkum cara konsep Algoritma & Struktur Data biasanya diubah menjadi pertanyaan pilihan ganda. Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.', '["Soal definisi","Soal perbandingan konsep","Soal studi kasus singkat","Distraktor jawaban yang mirip"]'::jsonb, 4);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (3, 'Istilah Dasar', '📘', 'Ringkas', 'Bagian ini mengenalkan istilah dasar dalam Basis Data sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.', '["Definisi konsep utama","Fungsi setiap istilah","Perbedaan istilah yang mirip","Contoh penerapan secara umum"]'::jsonb, 1);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (3, 'Konsep Inti', '🧠', 'Teori', 'Konsep inti menjelaskan prinsip yang membuat Basis Data bekerja sebagai sebuah bidang ilmu. Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.', '["Prinsip kerja utama","Masalah yang diselesaikan","Kelebihan dan batasan konsep","Hubungan sebab-akibat"]'::jsonb, 2);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (3, 'Hubungan Antar Konsep', '🔗', 'Analisis', 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.', '["Konsep prasyarat","Konsep pembanding","Dampak perubahan sistem","Pola hubungan dalam soal"]'::jsonb, 3);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (3, 'Pola Soal Kuis', '🎯', 'Kuis', 'Bagian ini merangkum cara konsep Basis Data biasanya diubah menjadi pertanyaan pilihan ganda. Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.', '["Soal definisi","Soal perbandingan konsep","Soal studi kasus singkat","Distraktor jawaban yang mirip"]'::jsonb, 4);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (4, 'Istilah Dasar', '📘', 'Ringkas', 'Bagian ini mengenalkan istilah dasar dalam Jaringan Komputer sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.', '["Definisi konsep utama","Fungsi setiap istilah","Perbedaan istilah yang mirip","Contoh penerapan secara umum"]'::jsonb, 1);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (4, 'Konsep Inti', '🧠', 'Teori', 'Konsep inti menjelaskan prinsip yang membuat Jaringan Komputer bekerja sebagai sebuah bidang ilmu. Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.', '["Prinsip kerja utama","Masalah yang diselesaikan","Kelebihan dan batasan konsep","Hubungan sebab-akibat"]'::jsonb, 2);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (4, 'Hubungan Antar Konsep', '🔗', 'Analisis', 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.', '["Konsep prasyarat","Konsep pembanding","Dampak perubahan sistem","Pola hubungan dalam soal"]'::jsonb, 3);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (4, 'Pola Soal Kuis', '🎯', 'Kuis', 'Bagian ini merangkum cara konsep Jaringan Komputer biasanya diubah menjadi pertanyaan pilihan ganda. Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.', '["Soal definisi","Soal perbandingan konsep","Soal studi kasus singkat","Distraktor jawaban yang mirip"]'::jsonb, 4);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (5, 'Istilah Dasar', '📘', 'Ringkas', 'Bagian ini mengenalkan istilah dasar dalam Kecerdasan Buatan sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.', '["Definisi konsep utama","Fungsi setiap istilah","Perbedaan istilah yang mirip","Contoh penerapan secara umum"]'::jsonb, 1);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (5, 'Konsep Inti', '🧠', 'Teori', 'Konsep inti menjelaskan prinsip yang membuat Kecerdasan Buatan bekerja sebagai sebuah bidang ilmu. Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.', '["Prinsip kerja utama","Masalah yang diselesaikan","Kelebihan dan batasan konsep","Hubungan sebab-akibat"]'::jsonb, 2);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (5, 'Hubungan Antar Konsep', '🔗', 'Analisis', 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.', '["Konsep prasyarat","Konsep pembanding","Dampak perubahan sistem","Pola hubungan dalam soal"]'::jsonb, 3);
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES (5, 'Pola Soal Kuis', '🎯', 'Kuis', 'Bagian ini merangkum cara konsep Kecerdasan Buatan biasanya diubah menjadi pertanyaan pilihan ganda. Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.', '["Soal definisi","Soal perbandingan konsep","Soal studi kasus singkat","Distraktor jawaban yang mirip"]'::jsonb, 4);

-- ─── Game levels (12 level, 10 soal each) ──────────────────────────────────
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (1, 1, 'Pemanasan', 'Dasar Komputer', 0, 0, 0, 10, 'selesai', 3, 1);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (2, 5, 'Konsep Inti', 'Algoritma', 1, 1, 0, 10, 'selesai', 3, 2);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (3, 2, 'Latihan Cepat', 'Pemrograman', 2, 0, 1, 10, 'selesai', 2, 3);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (4, 13, 'Misi Aktif', 'Jaringan Komputer', 3, 3, 0, 10, 'aktif', 0, 4);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (5, 16, 'Tantangan Baru', 'Keamanan Digital', 4, 3, 3, 10, 'terkunci', 0, 5);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (6, 3, 'Combo Soal', 'Dasar Komputer', 0, 0, 2, 10, 'terkunci', 0, 6);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (7, 6, 'Mode Fokus', 'Algoritma', 1, 1, 1, 10, 'terkunci', 0, 7);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (8, 4, 'Boss Quiz', 'Pemrograman', 2, 0, 3, 10, 'terkunci', 0, 8);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (9, 14, 'Speed Run', 'Jaringan Komputer', 3, 3, 1, 10, 'terkunci', 0, 9);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (10, 15, 'Final Stage', 'Keamanan Digital', 4, 3, 2, 10, 'terkunci', 0, 10);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (11, 7, 'Bonus Map', 'Dasar Komputer', 0, 1, 2, 10, 'terkunci', 0, 11);
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (12, 8, 'Master Quiz', 'Algoritma', 1, 1, 3, 10, 'terkunci', 0, 12);

-- ─── Questions (10 per level) ────────────────────────────────────────────
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Dasar Komputer', 'Bagian komputer yang bertugas memproses instruksi utama adalah...', '["RAM","CPU","SSD","Monitor","GPU"]'::jsonb, 1, 'CPU (Central Processing Unit) adalah otak komputer yang menjalankan semua instruksi program.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Dasar Komputer', 'Komponen yang berfungsi sebagai memori jangka pendek saat program berjalan adalah...', '["Hard Disk","CPU","RAM","ROM","GPU"]'::jsonb, 2, 'RAM menyimpan data sementara yang dibutuhkan program yang sedang aktif.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Dasar Komputer', 'Satuan kecepatan prosesor yang paling umum digunakan saat ini adalah...', '["MHz","GHz","KB/s","MB/s","Watt"]'::jsonb, 1, 'GHz (Gigahertz) menunjukkan berapa miliar siklus per detik yang dapat dilakukan prosesor.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Dasar Komputer', 'Perangkat output yang menampilkan hasil kerja komputer secara visual adalah...', '["Keyboard","Mouse","Printer","Monitor","Scanner"]'::jsonb, 3, 'Monitor adalah perangkat output utama yang menampilkan informasi visual.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Dasar Komputer', 'Penyimpanan yang tetap menyimpan data meskipun komputer dimatikan disebut...', '["RAM","Cache","Register","ROM","Virtual Memory"]'::jsonb, 3, 'ROM dan storage seperti SSD/HDD menyimpan data secara permanen meski daya dimatikan.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Dasar Komputer', 'Perangkat yang berfungsi sebagai INPUT pada komputer adalah...', '["Monitor","Printer","Speaker","Scanner","Proyektor"]'::jsonb, 3, 'Scanner mengubah dokumen fisik menjadi data digital — fungsi INPUT.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Dasar Komputer', '1 Gigabyte (GB) setara dengan berapa Megabyte (MB)?', '["100 MB","512 MB","1000 MB","1024 MB","2048 MB"]'::jsonb, 3, 'Dalam sistem biner, 1 GB = 1024 MB.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Dasar Komputer', 'GPU paling utama digunakan untuk...', '["Menyimpan file permanen","Mengatur koneksi internet","Memproses grafis dan komputasi paralel","Membaca input keyboard","Menyimpan instruksi BIOS"]'::jsonb, 2, 'GPU dirancang untuk memproses grafis secara paralel dalam jumlah besar.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Dasar Komputer', 'Motherboard pada komputer berfungsi sebagai...', '["Menyimpan data permanen","Menghubungkan komponen utama","Menampilkan grafis","Mengatur suhu ruangan","Mencetak dokumen"]'::jsonb, 1, 'Motherboard adalah papan induk yang menghubungkan CPU, RAM, storage, dan komponen lain.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Dasar Komputer', 'Windows, Linux, dan macOS termasuk jenis...', '["Perangkat keras","Sistem operasi","Aplikasi office","Protokol jaringan","Bahasa pemrograman"]'::jsonb, 1, 'Sistem operasi mengelola hardware dan menyediakan antarmuka untuk aplikasi.'
FROM game_levels WHERE level_number = 1;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Algoritma', 'Algoritma paling tepat diartikan sebagai...', '["Bahasa komputer","Urutan langkah logis untuk menyelesaikan masalah","Tempat menyimpan file","Aplikasi desain","Kumpulan hardware"]'::jsonb, 1, 'Algoritma adalah serangkaian langkah terstruktur untuk menyelesaikan masalah.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Algoritma', 'Struktur kontrol untuk mengulang blok kode selama kondisi terpenuhi disebut...', '["Kondisional","Fungsi","Perulangan (Loop)","Array","Rekursi"]'::jsonb, 2, 'Perulangan (loop) mengeksekusi blok kode berulang kali.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Algoritma', 'Metode pencarian yang memeriksa setiap elemen satu per satu disebut...', '["Binary Search","Linear Search","Hash Search","Tree Search","Jump Search"]'::jsonb, 1, 'Linear Search memeriksa setiap elemen secara berurutan.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Algoritma', 'Kompleksitas waktu O(n) artinya...', '["Waktu konstan","Waktu bertambah seiring jumlah data","Waktu berkurang seiring data","Waktu kuadrat","Tidak butuh waktu"]'::jsonb, 1, 'O(n) berarti waktu eksekusi bertumbuh linear seiring input.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Algoritma', 'Algoritma pengurutan dengan membandingkan elemen berdekatan secara berulang disebut...', '["Merge Sort","Quick Sort","Bubble Sort","Selection Sort","Insertion Sort"]'::jsonb, 2, 'Bubble Sort membandingkan dua elemen berdekatan dan menukarnya jika salah urut.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Algoritma', 'Binary Search hanya dapat digunakan pada data yang...', '["Jumlahnya genap","Tersimpan di database","Sudah terurut (sorted)","Berupa bilangan bulat","Lebih dari 100 elemen"]'::jsonb, 2, 'Binary Search membagi data menjadi dua setiap langkah, butuh data terurut.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Algoritma', 'Kompleksitas O(log n) dimiliki oleh algoritma...', '["Bubble Sort","Linear Search","Binary Search","Selection Sort","Insertion Sort"]'::jsonb, 2, 'Binary Search memiliki kompleksitas O(log n).'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Algoritma', 'Struktur data LIFO (Last In, First Out) disebut...', '["Queue","Stack","Linked List","Tree","Graph"]'::jsonb, 1, 'Stack: elemen terakhir masuk adalah yang pertama keluar (LIFO).'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Algoritma', 'Struktur data FIFO (First In, First Out) disebut...', '["Stack","Queue","Tree","Graph","Heap"]'::jsonb, 1, 'Queue: elemen pertama masuk adalah yang pertama keluar.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Algoritma', 'Linked List menyimpan elemen dengan...', '["Indeks numerik saja","Pointer ke elemen berikutnya","Hash otomatis","Urutan alfabet","File CSV"]'::jsonb, 1, 'Setiap node linked list berisi data dan referensi/pointer ke node berikutnya.'
FROM game_levels WHERE level_number = 2;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Pemrograman', 'Apa fungsi variabel dalam program?', '["Menyimpan nilai yang bisa digunakan kembali","Menghapus semua data","Mengubah komputer jadi server","Menggambar tampilan saja","Mengatur koneksi internet"]'::jsonb, 0, 'Variabel adalah wadah bernama untuk menyimpan data.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Pemrograman', 'Konsep OOP untuk mewarisi properti dari kelas lain disebut...', '["Enkapsulasi","Polimorfisme","Abstraksi","Inheritance","Overloading"]'::jsonb, 3, 'Inheritance memungkinkan class anak mewarisi atribut class induk.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Pemrograman', 'Blok kode yang dapat dipanggil berulang dengan nama tertentu disebut...', '["Variabel","Konstanta","Fungsi","Komentar","Tipe Data"]'::jsonb, 2, 'Fungsi adalah blok kode bernama yang dapat dipanggil kapan pun.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Pemrograman', 'Tipe data dengan nilai true atau false disebut...', '["Integer","String","Float","Boolean","Char"]'::jsonb, 3, 'Boolean hanya memiliki dua nilai: true atau false.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Pemrograman', 'Proses mengubah kode sumber menjadi kode mesin disebut...', '["Debugging","Compiling","Refactoring","Testing","Deploying"]'::jsonb, 1, 'Compiling menerjemahkan kode sumber menjadi kode mesin.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Pemrograman', 'Prinsip OOP yang menyembunyikan detail implementasi disebut...', '["Inheritance","Polimorfisme","Enkapsulasi","Abstraksi","Overriding"]'::jsonb, 2, 'Enkapsulasi menyembunyikan detail internal objek.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Pemrograman', 'Array adalah struktur data yang...', '["Menyimpan elemen dalam urutan linier","Hanya bisa menyimpan teks","Tidak bisa diubah ukurannya","Hanya untuk angka desimal","Otomatis terurut"]'::jsonb, 0, 'Array menyimpan elemen dalam urutan linier dengan indeks.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Pemrograman', 'Kondisional if-else digunakan untuk...', '["Mengulang kode","Mengambil keputusan berdasarkan kondisi","Menyimpan data","Menghapus variabel","Mengompilasi program"]'::jsonb, 1, 'If-else mengeksekusi kode berbeda berdasarkan kondisi boolean.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Pemrograman', 'Tipe data untuk teks/kalimat disebut...', '["Integer","Boolean","String","Void","Pointer"]'::jsonb, 2, 'String (atau char array) menyimpan rangkaian karakter/teks.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Pemrograman', 'Tipe data 3.14 biasanya disimpan sebagai...', '["Boolean","Integer","Float/Double","Char saja","Null"]'::jsonb, 2, 'Bilangan desimal disimpan dalam tipe floating-point seperti float/double.'
FROM game_levels WHERE level_number = 3;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Jaringan Komputer', 'Protokol standar untuk halaman web adalah...', '["FTP","HTTP","SMTP","SSH","DNS"]'::jsonb, 1, 'HTTP (HyperText Transfer Protocol) adalah protokol standar web.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Jaringan Komputer', 'Alamat IP versi 4 terdiri dari...', '["2 oktet","4 oktet","6 oktet","8 oktet","16 oktet"]'::jsonb, 1, 'IPv4 terdiri dari 4 oktet (32 bit), ditulis xxx.xxx.xxx.xxx.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Jaringan Komputer', 'Model OSI memiliki berapa layer?', '["4","5","6","7","8"]'::jsonb, 3, 'Model OSI memiliki 7 layer standar komunikasi jaringan.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Jaringan Komputer', 'DNS berfungsi untuk...', '["Mengenkripsi data","Menerjemahkan nama domain ke alamat IP","Mengirim email","Mengompresi file","Mengatur firewall"]'::jsonb, 1, 'DNS menerjemahkan nama domain (google.com) menjadi alamat IP.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Jaringan Komputer', 'Layer OSI yang menangani routing paket data adalah...', '["Layer 1","Layer 2","Layer 3","Layer 4","Layer 7"]'::jsonb, 2, 'Layer 3 (Network) bertanggung jawab atas pengalamatan IP dan routing.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Jaringan Komputer', 'Protokol yang menjamin pengiriman data andal dan berurutan adalah...', '["UDP","TCP","ICMP","ARP","DHCP"]'::jsonb, 1, 'TCP memastikan data terkirim lengkap, berurutan, dan tanpa error.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Jaringan Komputer', 'Router berfungsi untuk...', '["Menyimpan file","Meneruskan paket data antar jaringan","Mencetak dokumen","Mengenkripsi password","Menampilkan grafis"]'::jsonb, 1, 'Router meneruskan paket data antar jaringan berbeda.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Jaringan Komputer', 'Port default untuk HTTPS adalah...', '["21","25","80","443","8080"]'::jsonb, 3, 'HTTPS menggunakan port 443 untuk komunikasi web terenkripsi.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Jaringan Komputer', 'LAN (Local Area Network) mencakup area...', '["Seluruh benua","Terbatas seperti gedung/kampus","Hanya satelit","Deep ocean","Antar planet"]'::jsonb, 1, 'LAN menghubungkan perangkat dalam area geografis terbatas.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Jaringan Komputer', 'WAN (Wide Area Network) biasanya...', '["Hanya satu ruangan","Menghubungkan jaringan jarak jauh/lebih luas","Tidak pakai router","Hanya Bluetooth","Tanpa protokol"]'::jsonb, 1, 'WAN seperti internet menghubungkan jaringan di kota/negara berbeda.'
FROM game_levels WHERE level_number = 4;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Keamanan Digital', 'Kebiasaan paling aman untuk menjaga akun adalah...', '["Password sama di semua app","Bagikan OTP ke teman","Simpan password di catatan HP","Aktifkan autentikasi dua faktor","Nama sendiri sebagai password"]'::jsonb, 3, '2FA menambah lapisan keamanan ekstra selain password.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Keamanan Digital', 'Serangan yang menipu user agar memberikan info sensitif disebut...', '["Malware","Ransomware","Phishing","DDoS","Brute Force"]'::jsonb, 2, 'Phishing menyamar sebagai entitas terpercaya untuk mencuri data.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Keamanan Digital', 'Malware yang mengenkripsi file dan meminta tebusan disebut...', '["Spyware","Adware","Ransomware","Trojan","Worm"]'::jsonb, 2, 'Ransomware mengenkripsi file dan meminta pembayaran tebusan.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Keamanan Digital', 'Proses mengubah data menjadi format tidak terbaca tanpa kunci disebut...', '["Kompresi","Enkripsi","Dekripsi","Hashing","Encoding"]'::jsonb, 1, 'Enkripsi mengubah data menjadi ciphertext menggunakan kunci.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Keamanan Digital', 'Jaringan privat virtual yang mengamankan koneksi internet disebut...', '["Firewall","Antivirus","VPN","Proxy","SSL"]'::jsonb, 2, 'VPN mengenkripsi lalu lintas internet dan menyembunyikan identitas.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Keamanan Digital', 'Malware yang memantau aktivitas pengguna diam-diam disebut...', '["Ransomware","Spyware","Adware","Bootkit","Keylogger"]'::jsonb, 1, 'Spyware memantau aktivitas dan mencuri data secara diam-diam.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Keamanan Digital', 'Hashing berbeda dari enkripsi karena...', '["Lebih lambat","Butuh kunci rahasia","Bersifat satu arah — tidak bisa dibalik","Hanya untuk jaringan","Hasil file lebih besar"]'::jsonb, 2, 'Hashing one-way — tidak bisa di-decrypt. Dipakai untuk password.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Keamanan Digital', 'Serangan yang membanjiri server dengan permintaan palsu disebut...', '["Phishing","Man-in-the-Middle","SQL Injection","DDoS","Brute Force"]'::jsonb, 3, 'DDoS membanjiri server hingga layanan tidak dapat diakses.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Keamanan Digital', 'Antivirus dirancang untuk...', '["Mempercepat internet","Mendeteksi dan mencegah malware","Mengganti password Wi-Fi","Mengompilasi program","Mengatur DHCP"]'::jsonb, 1, 'Antivirus memindai file/proses mencurigakan dan malware known signatures.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Keamanan Digital', 'Social engineering menyerang...', '["Hanya firewall","Psikologi/manipulasi manusia","Kabel fiber","Compiler","Database index"]'::jsonb, 1, 'Social engineering memanipulasi orang agar memberi akses/info rahasia.'
FROM game_levels WHERE level_number = 5;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Dasar Komputer', 'Unit data terkecil dalam komputasi disebut...', '["Byte","Nibble","Bit","Kilobit","Word"]'::jsonb, 2, 'Bit (binary digit) adalah unit data terkecil, bernilai 0 atau 1.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Dasar Komputer', 'Microsoft Word dan Google Chrome termasuk contoh...', '["Sistem operasi","Perangkat keras","Perangkat lunak aplikasi","Firmware","Driver jaringan"]'::jsonb, 2, 'Aplikasi adalah program yang dijalankan pengguna untuk tugas tertentu.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Dasar Komputer', 'Port USB pada komputer digunakan untuk...', '["Menyimpan BIOS","Menghubungkan periferal","Mengganti CPU","Meningkatkan RAM internal","Mengatur DNS"]'::jsonb, 1, 'Port USB menghubungkan keyboard, mouse, flash drive, dan perangkat lain.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Dasar Komputer', 'Keunggulan utama SSD dibanding HDD tradisional adalah...', '["Kapasitas lebih murah per GB","Tidak perlu daya","Akses data jauh lebih cepat","Hanya untuk backup","Tidak bisa rusak"]'::jsonb, 2, 'SSD menggunakan memori flash sehingga baca/tulis jauh lebih cepat dari disk magnetik.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Dasar Komputer', 'Cache pada prosesor berfungsi untuk...', '["Menyimpan file user","Mempercepat akses data yang sering dipakai","Mengganti RAM","Mengatur jaringan Wi-Fi","Menampilkan wallpaper"]'::jsonb, 1, 'Cache menyimpan salinan data/instruksi yang sering diakses agar CPU tidak menunggu RAM.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Dasar Komputer', 'Speaker dan headphone termasuk perangkat...', '["Input","Output","Storage","Processing","Network"]'::jsonb, 1, 'Speaker mengeluarkan suara sebagai hasil pemrosesan — kategori output.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Dasar Komputer', 'Bluetooth pada laptop digunakan untuk...', '["Menyimpan file cloud","Koneksi nirkabel jarak dekat","Mengganti sistem operasi","Mengompilasi program","Mengatur firewall"]'::jsonb, 1, 'Bluetooth adalah teknologi nirkabel jarak pendek untuk headset, mouse, dll.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Dasar Komputer', 'UPS (Uninterruptible Power Supply) berguna saat...', '["Internet lambat","Listrik padam sementara","Hard disk penuh","Layar retak","Keyboard rusak"]'::jsonb, 1, 'UPS memberi daya cadangan agar komputer bisa dimatikan aman saat listrik mati.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Dasar Komputer', 'Fitur multitasking pada OS memungkinkan...', '["Satu program saja berjalan","Beberapa program berjalan bergantian/paralel","Menghapus semua file","Mengganti hardware otomatis","Mematikan antivirus"]'::jsonb, 1, 'Multitasking membuat OS dapat menjalankan lebih dari satu aplikasi.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Dasar Komputer', 'Virtual memory memanfaatkan...', '["Monitor kedua","Sebagian ruang storage sebagai perpanjangan RAM","Kartu grafis","Port serial","Printer"]'::jsonb, 1, 'OS dapat memindahkan data RAM ke disk sementara ketika memori fisik penuh.'
FROM game_levels WHERE level_number = 6;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Algoritma', 'Merge Sort menggunakan strategi...', '["Brute force","Divide and Conquer","Greedy murni","Random walk","Linear scan"]'::jsonb, 1, 'Merge Sort membagi array, mengurutkan bagian, lalu menggabungkannya.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Algoritma', 'Quick Sort memilih elemen acuan (pivot) untuk...', '["Menghapus data","Membagi data menjadi dua bagian","Mengenkripsi array","Menyimpan di stack saja","Mencetak log"]'::jsonb, 1, 'Pivot dipakai mempartisi elemen lebih kecil dan lebih besar darinya.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Algoritma', 'Rekursi terjadi ketika fungsi...', '["Tidak pernah berhenti","Memanggil dirinya sendiri","Hanya dipakai di Python","Mengganti loop selamanya","Menghapus array"]'::jsonb, 1, 'Rekursi adalah fungsi yang memanggil dirinya dengan basis dan langkah rekursif.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Algoritma', 'Notasi Big O O(1) artinya waktu eksekusi...', '["Linear","Konstan terhadap ukuran input","Eksponensial","Logaritmik","Tidak terdefinisi"]'::jsonb, 1, 'O(1) berarti operasi membutuhkan waktu tetap meski data bertambah.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Algoritma', 'Graph terdiri dari...', '["Hanya angka","Vertex (simpul) dan edge (sisi)","Baris spreadsheet","File teks","Pointer null saja"]'::jsonb, 1, 'Graph memodelkan relasi antar objek dengan simpul dan sisi.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Algoritma', 'Pada struktur Tree, setiap node (kecuali root) memiliki...', '["Tiga parent","Satu parent","Tidak ada data","Indeks hash","Port jaringan"]'::jsonb, 1, 'Tree hierarkis: setiap node anak punya tepat satu induk.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Algoritma', 'Hash table rata-rata memberikan pencarian...', '["O(n²)","O(1) pada kondisi baik","O(log log n)","O(n log n) selalu","O(0)"]'::jsonb, 1, 'Dengan fungsi hash baik, lookup/insert/delete rata-rata O(1).'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Algoritma', 'Dynamic Programming dipakai untuk...', '["Masalah dengan sub-masalah tumpang tindih","Sortir file saja","Mengganti hardware","Menghapus graph","Mencetak PDF"]'::jsonb, 0, 'DP menyimpan hasil sub-masalah agar tidak dihitung ulang.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Algoritma', 'Algoritma greedy memilih...', '["Solusi optimal global selalu","Pilihan lokal terbaik saat ini","Semua kemungkinan brute force","Data acak","Urutan terbalik"]'::jsonb, 1, 'Greedy mengambil keputusan terbaik lokal di setiap langkah.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Algoritma', 'Depth-First Search (DFS) mengeksplorasi graph dengan...', '["Antrian level demi level","Menyelam sedalam mungkin dulu","Sortir ascending","Hash random","Binary split saja"]'::jsonb, 1, 'DFS pergi sedalam mungkin sebelum backtrack ke cabang lain.'
FROM game_levels WHERE level_number = 7;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Pemrograman', 'Tipe Integer digunakan untuk...', '["Teks panjang","Bilangan bulat","True/false","File biner saja","HTML"]'::jsonb, 1, 'Integer menyimpan nilai numerik tanpa bagian desimal.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Pemrograman', 'Komentar dalam kode sumber berguna untuk...', '["Menjalankan program lebih cepat","Menjelaskan kode tanpa dieksekusi","Mengganti compiler","Menghapus bug otomatis","Mengenkripsi file"]'::jsonb, 1, 'Komentar diabaikan compiler/interpreter dan membantu dokumentasi.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Pemrograman', 'Debugging adalah proses...', '["Menulis kode pertama kali","Mencari dan memperbaiki error","Deploy ke server","Desain UI","Backup database"]'::jsonb, 1, 'Debugging menelusuri dan memperbaiki bug/defect dalam program.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Pemrograman', 'IDE (Integrated Development Environment) menyediakan...', '["Hanya text editor biasa","Editor, debugger, dan build tools terintegrasi","Router Wi-Fi","Antivirus saja","Cloud storage saja"]'::jsonb, 1, 'IDE seperti VS Code/Android Studio menggabungkan alat pengembangan.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Pemrograman', 'API (Application Programming Interface) memungkinkan...', '["Program berkomunikasi dengan layanan/modul lain","Mengganti monitor","Mengetik lebih cepat","Menyimpan listrik","Mematikan OS"]'::jsonb, 0, 'API mendefinisikan cara program memanggil fungsi/layanan eksternal.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Pemrograman', 'Git digunakan terutama untuk...', '["Editing video","Version control kode sumber","Menggambar UI","Scan virus","Routing paket"]'::jsonb, 1, 'Git melacak perubahan kode dan kolaborasi antar developer.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Pemrograman', 'Loop for biasanya dipakai ketika...', '["Jumlah iterasi sudah diketahui","Tidak ada kondisi","Hanya satu statement","Program selesai","Tidak perlu variabel"]'::jsonb, 0, 'For loop cocok saat batas/perulangan sudah jelas (mis. 1..10).'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Pemrograman', 'Switch-case digunakan untuk...', '["Menyimpan array","Memilih aksi berdasarkan nilai diskret","Mengompilasi otomatis","Menghapus variabel","Mengatur jaringan"]'::jsonb, 1, 'Switch membandingkan variabel dengan beberapa case constant.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Pemrograman', 'Konstanta berbeda dari variabel karena...', '["Nilainya tidak boleh diubah setelah ditetapkan","Lebih lambat","Hanya untuk teks","Tidak punya nama","Hanya di Python"]'::jsonb, 0, 'Konstanta (const/final) nilainya fixed selama program berjalan.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Pemrograman', 'Nilai null/nil pada variabel objek berarti...', '["Objek sedang error fatal","Tidak mereferensikan objek apapun","Objek paling besar","String kosong saja","Integer nol"]'::jsonb, 1, 'Null/nil menandakan absence of object reference.'
FROM game_levels WHERE level_number = 8;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Jaringan Komputer', 'Alamat MAC identifikasi unik perangkat di...', '["Layer aplikasi saja","Layer data link (NIC)","Layer presentasi","Cloud storage","Browser cache"]'::jsonb, 1, 'MAC address melekat pada kartu jaringan perangkat fisik.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Jaringan Komputer', 'Subnet mask digunakan untuk...', '["Mengenkripsi email","Membagi jaringan IP menjadi subnet","Mencetak dokumen","Mengompilasi kode","Scan malware"]'::jsonb, 1, 'Subnet mask menentukan bagian network ID dan host ID dari IP.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Jaringan Komputer', 'Firewall berfungsi untuk...', '["Mempercepat CPU","Menyaring lalu lintas jaringan","Menyimpan backup","Mengganti DNS","Mencetak label"]'::jsonb, 1, 'Firewall menerapkan aturan keamanan pada traffic masuk/keluar.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Jaringan Komputer', 'Perbedaan HTTP dan HTTPS adalah...', '["HTTPS tidak pakai port","HTTPS menambahkan enkripsi TLS/SSL","HTTP lebih aman","HTTPS hanya untuk email","Sama persis"]'::jsonb, 1, 'HTTPS = HTTP + enkripsi, melindungi data in-transit.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Jaringan Komputer', 'FTP digunakan untuk...', '["Kirim email","Transfer file antar host","Resolusi domain","Ping test","Routing OSPF"]'::jsonb, 1, 'File Transfer Protocol mentransfer file ke/dari server.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Jaringan Komputer', 'SMTP bertanggung jawab atas...', '["Browsing web","Pengiriman email","Streaming video","DNS lookup","SSH login"]'::jsonb, 1, 'Simple Mail Transfer Protocol mengirim email antar server.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Jaringan Komputer', 'Perintah ping menggunakan protokol...', '["TCP","ICMP","FTP","SMTP","SNMP"]'::jsonb, 1, 'Ping mengirim ICMP echo request untuk uji konektivitas.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Jaringan Komputer', 'NAT (Network Address Translation) berguna untuk...', '["Menerjemahkan domain","Memetakan IP privat ke IP publik","Mengenkripsi disk","Sortir paket","Compile Java"]'::jsonb, 1, 'NAT memungkinkan banyak perangkat lokal berbagi satu IP publik.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Jaringan Komputer', 'Wi-Fi bekerja pada layer OSI...', '["Layer 7 saja","Layer 1 dan 2 (fisik & data link)","Layer 5 saja","Tidak masuk OSI","Layer 8"]'::jsonb, 1, 'Wi-Fi IEEE 802.11 beroperasi di physical dan data link layer.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Jaringan Komputer', 'Kabel Ethernet umum di jaringan kantor termasuk media...', '["Nirkabel saja","Kabel tembaga twisted pair","Satelit","Laser medis","Ultrasonik"]'::jsonb, 1, 'Ethernet kabel UTP adalah media wired paling umum di LAN.'
FROM game_levels WHERE level_number = 9;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Keamanan Digital', 'SSL/TLS pada website berguna untuk...', '["Memperbesar font","Mengenkripsi komunikasi browser-server","Menghapus cookie","Mengganti DNS","Mempercepat CPU"]'::jsonb, 1, 'TLS melindungi data sensitif (login, kartu kredit) saat transit.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Keamanan Digital', 'Serangan brute force mencoba...', '["Satu password saja","Semua kombinasi password/kunci","Mematikan listrik","Mengganti MAC","Format hard disk otomatis"]'::jsonb, 1, 'Brute force mencoba kombinasi secara exhaustive sampai berhasil.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Keamanan Digital', 'Man-in-the-Middle (MitM) terjadi ketika...', '["Server mati","Penyerang menyadap/mengubah komunikasi di tengah","Password terlalu panjang","Backup gagal","Antivirus update"]'::jsonb, 1, 'MitM: attacker berada di antara dua pihak yang berkomunikasi.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Keamanan Digital', 'SQL Injection mengeksploitasi...', '["Input yang tidak divalidasi pada query database","Monitor retak","Kabel putus","Font CSS","Baterai laptop"]'::jsonb, 0, 'Input jahat dimasukkan ke query SQL sehingga database dieksploitasi.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Keamanan Digital', 'Cross-Site Scripting (XSS) menempatkan...', '["Virus di hardware","Script berbahaya di halaman web","Kabel tambahan","Firewall mati","DNS record A"]'::jsonb, 1, 'XSS menyisipkan script jahat yang dijalankan browser korban.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Keamanan Digital', 'Backup data rutin penting untuk...', '["Mempercepat CPU","Pemulihan setelah kehilangan data","Mengganti router","Menghapus malware otomatis","Meningkatkan FPS game"]'::jsonb, 1, 'Backup memungkinkan restore jika ransomware, human error, atau bencana.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Keamanan Digital', 'Password yang kuat biasanya...', '["Nama tanggal lahir","Panjang, acak, kombinasi karakter","Satu huruf saja","Sama dengan username","Kosong"]'::jsonb, 1, 'Password kuat: panjang, acak, campuran huruf/angka/simbol.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Keamanan Digital', 'Keylogger adalah malware yang...', '["Mencatat penekanan tombol keyboard","Mempercepat RAM","Mengganti wallpaper","Update OS","Scan port saja"]'::jsonb, 0, 'Keylogger merekam input keyboard untuk mencuri kredensial.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Keamanan Digital', 'Prinsip least privilege berarti user diberi...', '["Semua akses admin","Hanya hak minimum yang dibutuhkan","Akses tanpa password","Root selamanya","Token publik"]'::jsonb, 1, 'Least privilege mengurangi risiko jika akun disusupi.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Keamanan Digital', 'Phishing via SMS sering disebut...', '["Vishing","Smishing","DDoS","Hashing","Ping flood"]'::jsonb, 1, 'Smishing = SMS + phishing, menipu via pesan teks.'
FROM game_levels WHERE level_number = 10;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Dasar Komputer', 'Firmware biasa ditemukan pada...', '["Mouse saja","Chip perangkat seperti BIOS/UEFI","Kabel HDMI","Meja komputer","Stylus tablet"]'::jsonb, 1, 'Firmware adalah perangkat lunak yang tertanam di hardware, misalnya BIOS.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Dasar Komputer', '1 Byte setara dengan berapa bit?', '["4 bit","8 bit","16 bit","32 bit","1024 bit"]'::jsonb, 1, 'Standarnya 1 Byte = 8 bit.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Dasar Komputer', 'Mikrofon pada komputer termasuk perangkat...', '["Output","Input","Storage","Cooling","Routing"]'::jsonb, 1, 'Mikrofon menerima suara dari luar dan mengubahnya menjadi data digital.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Dasar Komputer', 'Thin client biasanya mengandalkan...', '["Server jarak jauh untuk pemrosesan","Hard disk 10 TB lokal","GPU gaming","Printer dot matrix","Kabel coaxial"]'::jsonb, 0, 'Thin client minim spesifikasi karena sebagian besar kerja dilakukan di server.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Dasar Komputer', 'Hotspot Wi-Fi berperan sebagai...', '["Penyimpanan cloud","Titik akses jaringan nirkabel","Antivirus","Compiler","Database"]'::jsonb, 1, 'Hotspot membagikan koneksi internet melalui Wi-Fi ke perangkat terdekat.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Dasar Komputer', 'Cloud storage seperti Google Drive menyimpan file di...', '["Floppy disk","Server pusat via internet","Cache CPU","Port USB","RAM saja"]'::jsonb, 1, 'Cloud storage menyimpan data di server remote yang diakses lewat internet.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Dasar Komputer', 'Layar sentuh (touchscreen) dapat berfungsi sebagai...', '["Hanya output","Input sekaligus output","Hanya storage","Hanya cooling","Hanya router"]'::jsonb, 1, 'Touchscreen menampilkan info (output) dan menerima sentuhan (input).'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Dasar Komputer', 'Proyektor termasuk perangkat...', '["Input","Output","Processing","Network switch","Power supply"]'::jsonb, 1, 'Proyektor menampilkan gambar dari komputer ke layar besar — perangkat output.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Dasar Komputer', 'Optical drive seperti DVD-ROM membaca data dari...', '["Chip SSD","Cakram optik","Kabel fiber","Magnet hard disk","Cloud saja"]'::jsonb, 1, 'Optical drive menggunakan laser untuk membaca/menulis cakram CD/DVD/Blu-ray.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Dasar Komputer', 'Hyper-Threading pada CPU memungkinkan...', '["Core fisik bertambah permanen","Satu core menjalankan lebih dari satu thread","RAM otomatis dobel","Monitor jadi touch","Internet lebih cepat"]'::jsonb, 1, 'Hyper-Threading membuat satu core fisik tampak sebagai dua logical core.'
FROM game_levels WHERE level_number = 11;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 1, 'Algoritma', 'Breadth-First Search (BFS) mengeksplorasi graph dengan...', '["Stack","Queue per level","Rekursi tanpa batas","Pivot Quick Sort","Merge saja"]'::jsonb, 1, 'BFS memeriksa semua tetangga level saat ini sebelum ke level berikutnya.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 2, 'Algoritma', 'Selection Sort bekerja dengan...', '["Menukar elemen berdekatan berulang","Mencari minimum/maksimum lalu menempatkannya","Membagi dua array","Hashing key","DFS pada tree"]'::jsonb, 1, 'Selection Sort memilih elemen terkecil/terbesar dan menaruhnya di posisi benar.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 3, 'Algoritma', 'Insertion Sort efektif untuk data yang...', '["Sudah hampir terurut","Selalu acak besar","Berupa graph","Hanya satu elemen selamanya","Tersimpan di cloud"]'::jsonb, 0, 'Insertion Sort efisien pada data kecil atau hampir terurut.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 4, 'Algoritma', 'Heap Sort menggunakan struktur data...', '["Queue biasa","Binary Heap","Linked List ganda","Hash map saja","Stack kosong"]'::jsonb, 1, 'Heap Sort membangun max/min heap lalu mengambil elemen teratas berulang.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 5, 'Algoritma', 'Adjacency matrix merepresentasikan graph dengan...', '["Daftar linked list saja","Matriks 2D hubungan antar vertex","File JSON","Stack operasi","Queue FIFO saja"]'::jsonb, 1, 'Adjacency matrix pakai matriks n×n untuk menandai ada/tidaknya sisi.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 6, 'Algoritma', 'Trade-off time-space dalam algoritma berarti...', '["Waktu dan memori tidak saling terkait","Mengorbankan memori untuk mempercepat waktu atau sebaliknya","Algoritma selalu O(1)","Data tidak boleh besar","Hanya untuk AI"]'::jsonb, 1, 'Sering kali kita tukar penggunaan memori extra dengan waktu lebih cepat.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 7, 'Algoritma', 'Algoritma divide and conquer umumnya terdiri dari...', '["Input, compile, deploy","Bagi, selesaikan, gabung","Hash, encrypt, send","Loop, break, return","Push, pop, peek"]'::jsonb, 1, 'Divide and conquer: split masalah, selesaikan sub-masalah, combine hasil.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 8, 'Algoritma', 'Sorting stabil artinya...', '["Tidak pernah error","Elemen sama mempertahankan urutan relatif awal","Selalu O(n)","Hanya untuk integer","Menggunakan stack"]'::jsonb, 1, 'Stable sort tidak mengubah urutan relatif elemen dengan kunci sama.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 9, 'Algoritma', 'Analisis amortized digunakan untuk...', '["Menghitung rata-rata biaya operasi dalam rangkaian","Mengukur suhu CPU","Mengatur DNS","Menyimpan password","Mencetak graph"]'::jsonb, 0, 'Amortized analysis melihat biaya rata-rata operasi over sequence.'
FROM game_levels WHERE level_number = 12;
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, 10, 'Algoritma', 'Deque (double-ended queue) memungkinkan...', '["Insert/delete hanya di depan","Insert/delete di kedua ujung","Hanya pop","Hanya sort","Hanya hash"]'::jsonb, 1, 'Deque mendukung operasi di front dan rear.'
FROM game_levels WHERE level_number = 12;
