#!/usr/bin/env dart
// Generates supabase/seed.sql from embedded question bank.
// Run: dart run tool/generate_seed.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final out = StringBuffer();
  out.writeln('-- KursusKilat seed — generated by tool/generate_seed.dart');
  out.writeln('');

  _writeCourses(out);
  _writeMaterials(out);
  _writeLevels(out);
  _writeQuestions(out);

  final path = '../../supabase/seed.sql';
  File(path).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $path (${out.length} chars)');
}

void _writeCourses(StringBuffer out) {
  out.writeln('-- ─── Courses ───────────────────────────────────────────────────────────────');
  const courses = [
    ('💻', 'PROGRAMMING', 'Dasar Pemrograman', 'Konsep variabel, tipe data, percabangan, perulangan, dan struktur program.', 4278190232, 4278190111, 1),
    ('🧮', 'ILMU KOMPUTER', 'Algoritma & Struktur Data', 'Cara data disusun, dicari, dibandingkan, dan diproses secara efisien.', 4278190506, 4278190111, 2),
    ('📊', 'DATABASE', 'Basis Data', 'Relasi data, kunci, normalisasi, transaksi, dan konsep penyimpanan informasi.', 4279308362, 4278190111, 3),
    ('🌐', 'NETWORKING', 'Jaringan Komputer', 'Protokol, alamat jaringan, model komunikasi, dan keamanan dasar jaringan.', 4286578701, 4283822093, 4),
    ('🤖', 'AI & ML', 'Kecerdasan Buatan', 'Konsep agen cerdas, pembelajaran mesin, data, model, dan evaluasi AI.', 4279508522, 4279508256, 5),
  ];
  for (final c in courses) {
    out.writeln("""
INSERT INTO courses (emoji, category, title, description, intro_video_url, total_duration, modules_total, accent_start, accent_end, sort_order)
VALUES ('${c.$1}', '${c.$2}', '${c.$3}', '${c.$4}', '', 'Materi teori', 4, ${c.$5}, ${c.$6}, ${c.$7});""");
  }
  out.writeln('');
}

void _writeMaterials(StringBuffer out) {
  out.writeln('-- ─── Materials (4 per course) ────────────────────────────────────────────');
  const moduleTemplates = [
    ('Istilah Dasar', '📘', 'Ringkas', 0),
    ('Konsep Inti', '🧠', 'Teori', 1),
    ('Hubungan Antar Konsep', '🔗', 'Analisis', 2),
    ('Pola Soal Kuis', '🎯', 'Kuis', 3),
  ];
  const courseTitles = [
    'Dasar Pemrograman',
    'Algoritma & Struktur Data',
    'Basis Data',
    'Jaringan Komputer',
    'Kecerdasan Buatan',
  ];
  for (var ci = 0; ci < courseTitles.length; ci++) {
    final ct = courseTitles[ci];
    final courseId = ci + 1;
    for (final m in moduleTemplates) {
      final content = _materialContent(ct, m.$1);
      final keyPoints = _keyPoints(m.$1);
      out.writeln("""
INSERT INTO materials (course_id, title, emoji, duration_label, content, key_points, sort_order)
VALUES ($courseId, '${m.$1}', '${m.$2}', '${m.$3}', ${_sqlStr(content)}, '${jsonEncode(keyPoints)}'::jsonb, ${m.$4 + 1});""");
    }
  }
  out.writeln('');
}

String _materialContent(String courseTitle, String moduleTitle) {
  switch (moduleTitle) {
    case 'Istilah Dasar':
      return 'Bagian ini mengenalkan istilah dasar dalam $courseTitle sebagai bahasa bersama sebelum masuk ke pembahasan yang lebih dalam. '
          'Dalam soal pilihan ganda, istilah dasar sering menjadi kunci karena satu kata dapat membedakan jawaban yang benar dan jawaban yang sekadar terdengar mirip.';
    case 'Konsep Inti':
      return 'Konsep inti menjelaskan prinsip yang membuat $courseTitle bekerja sebagai sebuah bidang ilmu. '
          'Bagian ini tidak berfokus pada langkah teknis, melainkan pada alasan mengapa suatu mekanisme digunakan.';
    case 'Hubungan Antar Konsep':
      return 'Dalam satu mata pelajaran, konsep jarang berdiri sendiri. Bagian ini disiapkan untuk soal yang menuntut pemahaman hubungan, bukan hafalan.';
    default:
      return 'Bagian ini merangkum cara konsep $courseTitle biasanya diubah menjadi pertanyaan pilihan ganda. '
          'Tujuannya bukan memberi bocoran jawaban, tetapi membiasakan user membaca soal secara konseptual.';
  }
}

List<String> _keyPoints(String moduleTitle) {
  switch (moduleTitle) {
    case 'Istilah Dasar':
      return ['Definisi konsep utama', 'Fungsi setiap istilah', 'Perbedaan istilah yang mirip', 'Contoh penerapan secara umum'];
    case 'Konsep Inti':
      return ['Prinsip kerja utama', 'Masalah yang diselesaikan', 'Kelebihan dan batasan konsep', 'Hubungan sebab-akibat'];
    case 'Hubungan Antar Konsep':
      return ['Konsep prasyarat', 'Konsep pembanding', 'Dampak perubahan sistem', 'Pola hubungan dalam soal'];
    default:
      return ['Soal definisi', 'Soal perbandingan konsep', 'Soal studi kasus singkat', 'Distraktor jawaban yang mirip'];
  }
}

void _writeLevels(StringBuffer out) {
  out.writeln('-- ─── Game levels (12 level, 10 soal each) ──────────────────────────────────');
  // (level_number, title, topic, topic_cat, course_idx, material_idx, default_status, default_stars, material_id)
  // material_id = course_idx*4 + material_idx + 1  (courses 1-5, materials 1-20)
  const levels = [
    (1, 'Pemanasan', 'Dasar Komputer', 0, 0, 0, 'selesai', 3),
    (2, 'Konsep Inti', 'Algoritma', 1, 1, 0, 'selesai', 3),
    (3, 'Latihan Cepat', 'Pemrograman', 2, 0, 1, 'selesai', 2),
    (4, 'Misi Aktif', 'Jaringan Komputer', 3, 3, 0, 'aktif', 0),
    (5, 'Tantangan Baru', 'Keamanan Digital', 4, 3, 3, 'terkunci', 0),
    (6, 'Combo Soal', 'Dasar Komputer', 0, 0, 2, 'terkunci', 0),
    (7, 'Mode Fokus', 'Algoritma', 1, 1, 1, 'terkunci', 0),
    (8, 'Boss Quiz', 'Pemrograman', 2, 0, 3, 'terkunci', 0),
    (9, 'Speed Run', 'Jaringan Komputer', 3, 3, 1, 'terkunci', 0),
    (10, 'Final Stage', 'Keamanan Digital', 4, 3, 2, 'terkunci', 0),
    (11, 'Bonus Map', 'Dasar Komputer', 0, 1, 2, 'terkunci', 0),
    (12, 'Master Quiz', 'Algoritma', 1, 1, 3, 'terkunci', 0),
  ];
  for (final l in levels) {
    final materialId = l.$5 * 4 + l.$6 + 1;
    out.writeln("""
INSERT INTO game_levels (level_number, material_id, title, topic, topic_category_index, course_index, material_index, questions_count, default_status, default_stars, sort_order)
VALUES (${l.$1}, $materialId, '${l.$2}', '${l.$3}', ${l.$4}, ${l.$5}, ${l.$6}, 10, '${l.$7}', ${l.$8}, ${l.$1});""");
  }
  out.writeln('');
}

void _writeQuestions(StringBuffer out) {
  out.writeln('-- ─── Questions (10 per level) ────────────────────────────────────────────');

  final byCat = <int, List<Map<String, dynamic>>>{};
  for (final q in [..._questionBank, ..._supplementaryQuestionBank]) {
    final idx = q['cat_idx'] as int;
    byCat.putIfAbsent(idx, () => []).add(q);
  }

  const levels = [
    (1, 0), (2, 1), (3, 2), (4, 3), (5, 4), (6, 0), (7, 1), (8, 2), (9, 3), (10, 4), (11, 0), (12, 1),
  ];

  final catSlot = <int, int>{};
  for (final l in levels) {
    final levelNum = l.$1;
    final catIdx = l.$2;
    final pool = byCat[catIdx] ?? [];
    final slot = catSlot[catIdx] ?? 0;
    catSlot[catIdx] = slot + 1;
    final start = slot * 10;

    if (pool.length < start + 10) {
      throw StateError(
        'Kategori $catIdx butuh ${start + 10} soal unik, tersedia ${pool.length}',
      );
    }

    final selected = pool.sublist(start, start + 10);
    final texts = selected.map((q) => q['question'] as String).toList();
    if (texts.toSet().length != 10) {
      throw StateError(
        'Level $levelNum punya soal duplikat: ${texts.where((t) => texts.where((x) => x == t).length > 1).toSet()}',
      );
    }

    for (var n = 0; n < 10; n++) {
      final q = selected[n];
      out.writeln("""
INSERT INTO questions (level_id, sort_order, category, question, options, answer_index, explanation)
SELECT id, ${n + 1}, ${_sqlStr(q['category'])}, ${_sqlStr(q['question'])}, '${jsonEncode(q['options'])}'::jsonb, ${q['answer_index']}, ${_sqlStr(q['explanation'])}
FROM game_levels WHERE level_number = $levelNum;""");
    }
  }
}

String _sqlStr(String s) => "'${s.replaceAll("'", "''")}'";

// cat_idx: 0=Dasar Komputer, 1=Algoritma, 2=Pemrograman, 3=Jaringan, 4=Keamanan
final _questionBank = [
  // ── 0: Dasar Komputer (8) ──
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Bagian komputer yang bertugas memproses instruksi utama adalah...', 'options': ['RAM', 'CPU', 'SSD', 'Monitor', 'GPU'], 'answer_index': 1, 'explanation': 'CPU (Central Processing Unit) adalah otak komputer yang menjalankan semua instruksi program.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Komponen yang berfungsi sebagai memori jangka pendek saat program berjalan adalah...', 'options': ['Hard Disk', 'CPU', 'RAM', 'ROM', 'GPU'], 'answer_index': 2, 'explanation': 'RAM menyimpan data sementara yang dibutuhkan program yang sedang aktif.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Satuan kecepatan prosesor yang paling umum digunakan saat ini adalah...', 'options': ['MHz', 'GHz', 'KB/s', 'MB/s', 'Watt'], 'answer_index': 1, 'explanation': 'GHz (Gigahertz) menunjukkan berapa miliar siklus per detik yang dapat dilakukan prosesor.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Perangkat output yang menampilkan hasil kerja komputer secara visual adalah...', 'options': ['Keyboard', 'Mouse', 'Printer', 'Monitor', 'Scanner'], 'answer_index': 3, 'explanation': 'Monitor adalah perangkat output utama yang menampilkan informasi visual.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Penyimpanan yang tetap menyimpan data meskipun komputer dimatikan disebut...', 'options': ['RAM', 'Cache', 'Register', 'ROM', 'Virtual Memory'], 'answer_index': 3, 'explanation': 'ROM dan storage seperti SSD/HDD menyimpan data secara permanen meski daya dimatikan.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Perangkat yang berfungsi sebagai INPUT pada komputer adalah...', 'options': ['Monitor', 'Printer', 'Speaker', 'Scanner', 'Proyektor'], 'answer_index': 3, 'explanation': 'Scanner mengubah dokumen fisik menjadi data digital — fungsi INPUT.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': '1 Gigabyte (GB) setara dengan berapa Megabyte (MB)?', 'options': ['100 MB', '512 MB', '1000 MB', '1024 MB', '2048 MB'], 'answer_index': 3, 'explanation': 'Dalam sistem biner, 1 GB = 1024 MB.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'GPU paling utama digunakan untuk...', 'options': ['Menyimpan file permanen', 'Mengatur koneksi internet', 'Memproses grafis dan komputasi paralel', 'Membaca input keyboard', 'Menyimpan instruksi BIOS'], 'answer_index': 2, 'explanation': 'GPU dirancang untuk memproses grafis secara paralel dalam jumlah besar.'},
  // ── 1: Algoritma (8) ──
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Algoritma paling tepat diartikan sebagai...', 'options': ['Bahasa komputer', 'Urutan langkah logis untuk menyelesaikan masalah', 'Tempat menyimpan file', 'Aplikasi desain', 'Kumpulan hardware'], 'answer_index': 1, 'explanation': 'Algoritma adalah serangkaian langkah terstruktur untuk menyelesaikan masalah.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Struktur kontrol untuk mengulang blok kode selama kondisi terpenuhi disebut...', 'options': ['Kondisional', 'Fungsi', 'Perulangan (Loop)', 'Array', 'Rekursi'], 'answer_index': 2, 'explanation': 'Perulangan (loop) mengeksekusi blok kode berulang kali.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Metode pencarian yang memeriksa setiap elemen satu per satu disebut...', 'options': ['Binary Search', 'Linear Search', 'Hash Search', 'Tree Search', 'Jump Search'], 'answer_index': 1, 'explanation': 'Linear Search memeriksa setiap elemen secara berurutan.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Kompleksitas waktu O(n) artinya...', 'options': ['Waktu konstan', 'Waktu bertambah seiring jumlah data', 'Waktu berkurang seiring data', 'Waktu kuadrat', 'Tidak butuh waktu'], 'answer_index': 1, 'explanation': 'O(n) berarti waktu eksekusi bertumbuh linear seiring input.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Algoritma pengurutan dengan membandingkan elemen berdekatan secara berulang disebut...', 'options': ['Merge Sort', 'Quick Sort', 'Bubble Sort', 'Selection Sort', 'Insertion Sort'], 'answer_index': 2, 'explanation': 'Bubble Sort membandingkan dua elemen berdekatan dan menukarnya jika salah urut.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Binary Search hanya dapat digunakan pada data yang...', 'options': ['Jumlahnya genap', 'Tersimpan di database', 'Sudah terurut (sorted)', 'Berupa bilangan bulat', 'Lebih dari 100 elemen'], 'answer_index': 2, 'explanation': 'Binary Search membagi data menjadi dua setiap langkah, butuh data terurut.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Kompleksitas O(log n) dimiliki oleh algoritma...', 'options': ['Bubble Sort', 'Linear Search', 'Binary Search', 'Selection Sort', 'Insertion Sort'], 'answer_index': 2, 'explanation': 'Binary Search memiliki kompleksitas O(log n).'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Struktur data LIFO (Last In, First Out) disebut...', 'options': ['Queue', 'Stack', 'Linked List', 'Tree', 'Graph'], 'answer_index': 1, 'explanation': 'Stack: elemen terakhir masuk adalah yang pertama keluar (LIFO).'},
  // ── 2: Pemrograman (8) ──
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Apa fungsi variabel dalam program?', 'options': ['Menyimpan nilai yang bisa digunakan kembali', 'Menghapus semua data', 'Mengubah komputer jadi server', 'Menggambar tampilan saja', 'Mengatur koneksi internet'], 'answer_index': 0, 'explanation': 'Variabel adalah wadah bernama untuk menyimpan data.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Konsep OOP untuk mewarisi properti dari kelas lain disebut...', 'options': ['Enkapsulasi', 'Polimorfisme', 'Abstraksi', 'Inheritance', 'Overloading'], 'answer_index': 3, 'explanation': 'Inheritance memungkinkan class anak mewarisi atribut class induk.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Blok kode yang dapat dipanggil berulang dengan nama tertentu disebut...', 'options': ['Variabel', 'Konstanta', 'Fungsi', 'Komentar', 'Tipe Data'], 'answer_index': 2, 'explanation': 'Fungsi adalah blok kode bernama yang dapat dipanggil kapan pun.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Tipe data dengan nilai true atau false disebut...', 'options': ['Integer', 'String', 'Float', 'Boolean', 'Char'], 'answer_index': 3, 'explanation': 'Boolean hanya memiliki dua nilai: true atau false.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Proses mengubah kode sumber menjadi kode mesin disebut...', 'options': ['Debugging', 'Compiling', 'Refactoring', 'Testing', 'Deploying'], 'answer_index': 1, 'explanation': 'Compiling menerjemahkan kode sumber menjadi kode mesin.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Prinsip OOP yang menyembunyikan detail implementasi disebut...', 'options': ['Inheritance', 'Polimorfisme', 'Enkapsulasi', 'Abstraksi', 'Overriding'], 'answer_index': 2, 'explanation': 'Enkapsulasi menyembunyikan detail internal objek.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Array adalah struktur data yang...', 'options': ['Menyimpan elemen dalam urutan linier', 'Hanya bisa menyimpan teks', 'Tidak bisa diubah ukurannya', 'Hanya untuk angka desimal', 'Otomatis terurut'], 'answer_index': 0, 'explanation': 'Array menyimpan elemen dalam urutan linier dengan indeks.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Kondisional if-else digunakan untuk...', 'options': ['Mengulang kode', 'Mengambil keputusan berdasarkan kondisi', 'Menyimpan data', 'Menghapus variabel', 'Mengompilasi program'], 'answer_index': 1, 'explanation': 'If-else mengeksekusi kode berbeda berdasarkan kondisi boolean.'},
  // ── 3: Jaringan Komputer (8) ──
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Protokol standar untuk halaman web adalah...', 'options': ['FTP', 'HTTP', 'SMTP', 'SSH', 'DNS'], 'answer_index': 1, 'explanation': 'HTTP (HyperText Transfer Protocol) adalah protokol standar web.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Alamat IP versi 4 terdiri dari...', 'options': ['2 oktet', '4 oktet', '6 oktet', '8 oktet', '16 oktet'], 'answer_index': 1, 'explanation': 'IPv4 terdiri dari 4 oktet (32 bit), ditulis xxx.xxx.xxx.xxx.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Model OSI memiliki berapa layer?', 'options': ['4', '5', '6', '7', '8'], 'answer_index': 3, 'explanation': 'Model OSI memiliki 7 layer standar komunikasi jaringan.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'DNS berfungsi untuk...', 'options': ['Mengenkripsi data', 'Menerjemahkan nama domain ke alamat IP', 'Mengirim email', 'Mengompresi file', 'Mengatur firewall'], 'answer_index': 1, 'explanation': 'DNS menerjemahkan nama domain (google.com) menjadi alamat IP.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Layer OSI yang menangani routing paket data adalah...', 'options': ['Layer 1', 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7'], 'answer_index': 2, 'explanation': 'Layer 3 (Network) bertanggung jawab atas pengalamatan IP dan routing.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Protokol yang menjamin pengiriman data andal dan berurutan adalah...', 'options': ['UDP', 'TCP', 'ICMP', 'ARP', 'DHCP'], 'answer_index': 1, 'explanation': 'TCP memastikan data terkirim lengkap, berurutan, dan tanpa error.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Router berfungsi untuk...', 'options': ['Menyimpan file', 'Meneruskan paket data antar jaringan', 'Mencetak dokumen', 'Mengenkripsi password', 'Menampilkan grafis'], 'answer_index': 1, 'explanation': 'Router meneruskan paket data antar jaringan berbeda.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Port default untuk HTTPS adalah...', 'options': ['21', '25', '80', '443', '8080'], 'answer_index': 3, 'explanation': 'HTTPS menggunakan port 443 untuk komunikasi web terenkripsi.'},
  // ── 4: Keamanan Digital (8) ──
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Kebiasaan paling aman untuk menjaga akun adalah...', 'options': ['Password sama di semua app', 'Bagikan OTP ke teman', 'Simpan password di catatan HP', 'Aktifkan autentikasi dua faktor', 'Nama sendiri sebagai password'], 'answer_index': 3, 'explanation': '2FA menambah lapisan keamanan ekstra selain password.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Serangan yang menipu user agar memberikan info sensitif disebut...', 'options': ['Malware', 'Ransomware', 'Phishing', 'DDoS', 'Brute Force'], 'answer_index': 2, 'explanation': 'Phishing menyamar sebagai entitas terpercaya untuk mencuri data.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Malware yang mengenkripsi file dan meminta tebusan disebut...', 'options': ['Spyware', 'Adware', 'Ransomware', 'Trojan', 'Worm'], 'answer_index': 2, 'explanation': 'Ransomware mengenkripsi file dan meminta pembayaran tebusan.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Proses mengubah data menjadi format tidak terbaca tanpa kunci disebut...', 'options': ['Kompresi', 'Enkripsi', 'Dekripsi', 'Hashing', 'Encoding'], 'answer_index': 1, 'explanation': 'Enkripsi mengubah data menjadi ciphertext menggunakan kunci.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Jaringan privat virtual yang mengamankan koneksi internet disebut...', 'options': ['Firewall', 'Antivirus', 'VPN', 'Proxy', 'SSL'], 'answer_index': 2, 'explanation': 'VPN mengenkripsi lalu lintas internet dan menyembunyikan identitas.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Malware yang memantau aktivitas pengguna diam-diam disebut...', 'options': ['Ransomware', 'Spyware', 'Adware', 'Bootkit', 'Keylogger'], 'answer_index': 1, 'explanation': 'Spyware memantau aktivitas dan mencuri data secara diam-diam.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Hashing berbeda dari enkripsi karena...', 'options': ['Lebih lambat', 'Butuh kunci rahasia', 'Bersifat satu arah — tidak bisa dibalik', 'Hanya untuk jaringan', 'Hasil file lebih besar'], 'answer_index': 2, 'explanation': 'Hashing one-way — tidak bisa di-decrypt. Dipakai untuk password.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Serangan yang membanjiri server dengan permintaan palsu disebut...', 'options': ['Phishing', 'Man-in-the-Middle', 'SQL Injection', 'DDoS', 'Brute Force'], 'answer_index': 3, 'explanation': 'DDoS membanjiri server hingga layanan tidak dapat diakses.'},
];

// Tambahan soal unik agar tiap level (10 soal) tidak wrap/duplikat.
// cat 0 dipakai level 1,6,11 → 30 soal | cat 1 level 2,7,12 → 30
// cat 2 level 3,8 → 20 | cat 3 level 4,9 → 20 | cat 4 level 5,10 → 20
final _supplementaryQuestionBank = [
  // ── 0: Dasar Komputer (+22 → total 30) ──
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Motherboard pada komputer berfungsi sebagai...', 'options': ['Menyimpan data permanen', 'Menghubungkan komponen utama', 'Menampilkan grafis', 'Mengatur suhu ruangan', 'Mencetak dokumen'], 'answer_index': 1, 'explanation': 'Motherboard adalah papan induk yang menghubungkan CPU, RAM, storage, dan komponen lain.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Windows, Linux, dan macOS termasuk jenis...', 'options': ['Perangkat keras', 'Sistem operasi', 'Aplikasi office', 'Protokol jaringan', 'Bahasa pemrograman'], 'answer_index': 1, 'explanation': 'Sistem operasi mengelola hardware dan menyediakan antarmuka untuk aplikasi.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Unit data terkecil dalam komputasi disebut...', 'options': ['Byte', 'Nibble', 'Bit', 'Kilobit', 'Word'], 'answer_index': 2, 'explanation': 'Bit (binary digit) adalah unit data terkecil, bernilai 0 atau 1.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Microsoft Word dan Google Chrome termasuk contoh...', 'options': ['Sistem operasi', 'Perangkat keras', 'Perangkat lunak aplikasi', 'Firmware', 'Driver jaringan'], 'answer_index': 2, 'explanation': 'Aplikasi adalah program yang dijalankan pengguna untuk tugas tertentu.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Port USB pada komputer digunakan untuk...', 'options': ['Menyimpan BIOS', 'Menghubungkan periferal', 'Mengganti CPU', 'Meningkatkan RAM internal', 'Mengatur DNS'], 'answer_index': 1, 'explanation': 'Port USB menghubungkan keyboard, mouse, flash drive, dan perangkat lain.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Keunggulan utama SSD dibanding HDD tradisional adalah...', 'options': ['Kapasitas lebih murah per GB', 'Tidak perlu daya', 'Akses data jauh lebih cepat', 'Hanya untuk backup', 'Tidak bisa rusak'], 'answer_index': 2, 'explanation': 'SSD menggunakan memori flash sehingga baca/tulis jauh lebih cepat dari disk magnetik.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Cache pada prosesor berfungsi untuk...', 'options': ['Menyimpan file user', 'Mempercepat akses data yang sering dipakai', 'Mengganti RAM', 'Mengatur jaringan Wi-Fi', 'Menampilkan wallpaper'], 'answer_index': 1, 'explanation': 'Cache menyimpan salinan data/instruksi yang sering diakses agar CPU tidak menunggu RAM.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Speaker dan headphone termasuk perangkat...', 'options': ['Input', 'Output', 'Storage', 'Processing', 'Network'], 'answer_index': 1, 'explanation': 'Speaker mengeluarkan suara sebagai hasil pemrosesan — kategori output.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Bluetooth pada laptop digunakan untuk...', 'options': ['Menyimpan file cloud', 'Koneksi nirkabel jarak dekat', 'Mengganti sistem operasi', 'Mengompilasi program', 'Mengatur firewall'], 'answer_index': 1, 'explanation': 'Bluetooth adalah teknologi nirkabel jarak pendek untuk headset, mouse, dll.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'UPS (Uninterruptible Power Supply) berguna saat...', 'options': ['Internet lambat', 'Listrik padam sementara', 'Hard disk penuh', 'Layar retak', 'Keyboard rusak'], 'answer_index': 1, 'explanation': 'UPS memberi daya cadangan agar komputer bisa dimatikan aman saat listrik mati.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Fitur multitasking pada OS memungkinkan...', 'options': ['Satu program saja berjalan', 'Beberapa program berjalan bergantian/paralel', 'Menghapus semua file', 'Mengganti hardware otomatis', 'Mematikan antivirus'], 'answer_index': 1, 'explanation': 'Multitasking membuat OS dapat menjalankan lebih dari satu aplikasi.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Virtual memory memanfaatkan...', 'options': ['Monitor kedua', 'Sebagian ruang storage sebagai perpanjangan RAM', 'Kartu grafis', 'Port serial', 'Printer'], 'answer_index': 1, 'explanation': 'OS dapat memindahkan data RAM ke disk sementara ketika memori fisik penuh.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Firmware biasa ditemukan pada...', 'options': ['Mouse saja', 'Chip perangkat seperti BIOS/UEFI', 'Kabel HDMI', 'Meja komputer', 'Stylus tablet'], 'answer_index': 1, 'explanation': 'Firmware adalah perangkat lunak yang tertanam di hardware, misalnya BIOS.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': '1 Byte setara dengan berapa bit?', 'options': ['4 bit', '8 bit', '16 bit', '32 bit', '1024 bit'], 'answer_index': 1, 'explanation': 'Standarnya 1 Byte = 8 bit.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Mikrofon pada komputer termasuk perangkat...', 'options': ['Output', 'Input', 'Storage', 'Cooling', 'Routing'], 'answer_index': 1, 'explanation': 'Mikrofon menerima suara dari luar dan mengubahnya menjadi data digital.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Thin client biasanya mengandalkan...', 'options': ['Server jarak jauh untuk pemrosesan', 'Hard disk 10 TB lokal', 'GPU gaming', 'Printer dot matrix', 'Kabel coaxial'], 'answer_index': 0, 'explanation': 'Thin client minim spesifikasi karena sebagian besar kerja dilakukan di server.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Hotspot Wi-Fi berperan sebagai...', 'options': ['Penyimpanan cloud', 'Titik akses jaringan nirkabel', 'Antivirus', 'Compiler', 'Database'], 'answer_index': 1, 'explanation': 'Hotspot membagikan koneksi internet melalui Wi-Fi ke perangkat terdekat.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Cloud storage seperti Google Drive menyimpan file di...', 'options': ['Floppy disk', 'Server pusat via internet', 'Cache CPU', 'Port USB', 'RAM saja'], 'answer_index': 1, 'explanation': 'Cloud storage menyimpan data di server remote yang diakses lewat internet.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Layar sentuh (touchscreen) dapat berfungsi sebagai...', 'options': ['Hanya output', 'Input sekaligus output', 'Hanya storage', 'Hanya cooling', 'Hanya router'], 'answer_index': 1, 'explanation': 'Touchscreen menampilkan info (output) dan menerima sentuhan (input).'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Proyektor termasuk perangkat...', 'options': ['Input', 'Output', 'Processing', 'Network switch', 'Power supply'], 'answer_index': 1, 'explanation': 'Proyektor menampilkan gambar dari komputer ke layar besar — perangkat output.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Optical drive seperti DVD-ROM membaca data dari...', 'options': ['Chip SSD', 'Cakram optik', 'Kabel fiber', 'Magnet hard disk', 'Cloud saja'], 'answer_index': 1, 'explanation': 'Optical drive menggunakan laser untuk membaca/menulis cakram CD/DVD/Blu-ray.'},
  {'cat_idx': 0, 'category': 'Dasar Komputer', 'question': 'Hyper-Threading pada CPU memungkinkan...', 'options': ['Core fisik bertambah permanen', 'Satu core menjalankan lebih dari satu thread', 'RAM otomatis dobel', 'Monitor jadi touch', 'Internet lebih cepat'], 'answer_index': 1, 'explanation': 'Hyper-Threading membuat satu core fisik tampak sebagai dua logical core.'},

  // ── 1: Algoritma (+22 → total 30) ──
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Struktur data FIFO (First In, First Out) disebut...', 'options': ['Stack', 'Queue', 'Tree', 'Graph', 'Heap'], 'answer_index': 1, 'explanation': 'Queue: elemen pertama masuk adalah yang pertama keluar.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Linked List menyimpan elemen dengan...', 'options': ['Indeks numerik saja', 'Pointer ke elemen berikutnya', 'Hash otomatis', 'Urutan alfabet', 'File CSV'], 'answer_index': 1, 'explanation': 'Setiap node linked list berisi data dan referensi/pointer ke node berikutnya.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Merge Sort menggunakan strategi...', 'options': ['Brute force', 'Divide and Conquer', 'Greedy murni', 'Random walk', 'Linear scan'], 'answer_index': 1, 'explanation': 'Merge Sort membagi array, mengurutkan bagian, lalu menggabungkannya.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Quick Sort memilih elemen acuan (pivot) untuk...', 'options': ['Menghapus data', 'Membagi data menjadi dua bagian', 'Mengenkripsi array', 'Menyimpan di stack saja', 'Mencetak log'], 'answer_index': 1, 'explanation': 'Pivot dipakai mempartisi elemen lebih kecil dan lebih besar darinya.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Rekursi terjadi ketika fungsi...', 'options': ['Tidak pernah berhenti', 'Memanggil dirinya sendiri', 'Hanya dipakai di Python', 'Mengganti loop selamanya', 'Menghapus array'], 'answer_index': 1, 'explanation': 'Rekursi adalah fungsi yang memanggil dirinya dengan basis dan langkah rekursif.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Notasi Big O O(1) artinya waktu eksekusi...', 'options': ['Linear', 'Konstan terhadap ukuran input', 'Eksponensial', 'Logaritmik', 'Tidak terdefinisi'], 'answer_index': 1, 'explanation': 'O(1) berarti operasi membutuhkan waktu tetap meski data bertambah.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Graph terdiri dari...', 'options': ['Hanya angka', 'Vertex (simpul) dan edge (sisi)', 'Baris spreadsheet', 'File teks', 'Pointer null saja'], 'answer_index': 1, 'explanation': 'Graph memodelkan relasi antar objek dengan simpul dan sisi.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Pada struktur Tree, setiap node (kecuali root) memiliki...', 'options': ['Tiga parent', 'Satu parent', 'Tidak ada data', 'Indeks hash', 'Port jaringan'], 'answer_index': 1, 'explanation': 'Tree hierarkis: setiap node anak punya tepat satu induk.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Hash table rata-rata memberikan pencarian...', 'options': ['O(n²)', 'O(1) pada kondisi baik', 'O(log log n)', 'O(n log n) selalu', 'O(0)'], 'answer_index': 1, 'explanation': 'Dengan fungsi hash baik, lookup/insert/delete rata-rata O(1).'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Dynamic Programming dipakai untuk...', 'options': ['Masalah dengan sub-masalah tumpang tindih', 'Sortir file saja', 'Mengganti hardware', 'Menghapus graph', 'Mencetak PDF'], 'answer_index': 0, 'explanation': 'DP menyimpan hasil sub-masalah agar tidak dihitung ulang.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Algoritma greedy memilih...', 'options': ['Solusi optimal global selalu', 'Pilihan lokal terbaik saat ini', 'Semua kemungkinan brute force', 'Data acak', 'Urutan terbalik'], 'answer_index': 1, 'explanation': 'Greedy mengambil keputusan terbaik lokal di setiap langkah.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Depth-First Search (DFS) mengeksplorasi graph dengan...', 'options': ['Antrian level demi level', 'Menyelam sedalam mungkin dulu', 'Sortir ascending', 'Hash random', 'Binary split saja'], 'answer_index': 1, 'explanation': 'DFS pergi sedalam mungkin sebelum backtrack ke cabang lain.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Breadth-First Search (BFS) mengeksplorasi graph dengan...', 'options': ['Stack', 'Queue per level', 'Rekursi tanpa batas', 'Pivot Quick Sort', 'Merge saja'], 'answer_index': 1, 'explanation': 'BFS memeriksa semua tetangga level saat ini sebelum ke level berikutnya.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Selection Sort bekerja dengan...', 'options': ['Menukar elemen berdekatan berulang', 'Mencari minimum/maksimum lalu menempatkannya', 'Membagi dua array', 'Hashing key', 'DFS pada tree'], 'answer_index': 1, 'explanation': 'Selection Sort memilih elemen terkecil/terbesar dan menaruhnya di posisi benar.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Insertion Sort efektif untuk data yang...', 'options': ['Sudah hampir terurut', 'Selalu acak besar', 'Berupa graph', 'Hanya satu elemen selamanya', 'Tersimpan di cloud'], 'answer_index': 0, 'explanation': 'Insertion Sort efisien pada data kecil atau hampir terurut.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Heap Sort menggunakan struktur data...', 'options': ['Queue biasa', 'Binary Heap', 'Linked List ganda', 'Hash map saja', 'Stack kosong'], 'answer_index': 1, 'explanation': 'Heap Sort membangun max/min heap lalu mengambil elemen teratas berulang.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Adjacency matrix merepresentasikan graph dengan...', 'options': ['Daftar linked list saja', 'Matriks 2D hubungan antar vertex', 'File JSON', 'Stack operasi', 'Queue FIFO saja'], 'answer_index': 1, 'explanation': 'Adjacency matrix pakai matriks n×n untuk menandai ada/tidaknya sisi.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Trade-off time-space dalam algoritma berarti...', 'options': ['Waktu dan memori tidak saling terkait', 'Mengorbankan memori untuk mempercepat waktu atau sebaliknya', 'Algoritma selalu O(1)', 'Data tidak boleh besar', 'Hanya untuk AI'], 'answer_index': 1, 'explanation': 'Sering kali kita tukar penggunaan memori extra dengan waktu lebih cepat.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Algoritma divide and conquer umumnya terdiri dari...', 'options': ['Input, compile, deploy', 'Bagi, selesaikan, gabung', 'Hash, encrypt, send', 'Loop, break, return', 'Push, pop, peek'], 'answer_index': 1, 'explanation': 'Divide and conquer: split masalah, selesaikan sub-masalah, combine hasil.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Sorting stabil artinya...', 'options': ['Tidak pernah error', 'Elemen sama mempertahankan urutan relatif awal', 'Selalu O(n)', 'Hanya untuk integer', 'Menggunakan stack'], 'answer_index': 1, 'explanation': 'Stable sort tidak mengubah urutan relatif elemen dengan kunci sama.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Analisis amortized digunakan untuk...', 'options': ['Menghitung rata-rata biaya operasi dalam rangkaian', 'Mengukur suhu CPU', 'Mengatur DNS', 'Menyimpan password', 'Mencetak graph'], 'answer_index': 0, 'explanation': 'Amortized analysis melihat biaya rata-rata operasi over sequence.'},
  {'cat_idx': 1, 'category': 'Algoritma', 'question': 'Deque (double-ended queue) memungkinkan...', 'options': ['Insert/delete hanya di depan', 'Insert/delete di kedua ujung', 'Hanya pop', 'Hanya sort', 'Hanya hash'], 'answer_index': 1, 'explanation': 'Deque mendukung operasi di front dan rear.'},

  // ── 2: Pemrograman (+12 → total 20) ──
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Tipe data untuk teks/kalimat disebut...', 'options': ['Integer', 'Boolean', 'String', 'Void', 'Pointer'], 'answer_index': 2, 'explanation': 'String (atau char array) menyimpan rangkaian karakter/teks.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Tipe data 3.14 biasanya disimpan sebagai...', 'options': ['Boolean', 'Integer', 'Float/Double', 'Char saja', 'Null'], 'answer_index': 2, 'explanation': 'Bilangan desimal disimpan dalam tipe floating-point seperti float/double.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Tipe Integer digunakan untuk...', 'options': ['Teks panjang', 'Bilangan bulat', 'True/false', 'File biner saja', 'HTML'], 'answer_index': 1, 'explanation': 'Integer menyimpan nilai numerik tanpa bagian desimal.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Komentar dalam kode sumber berguna untuk...', 'options': ['Menjalankan program lebih cepat', 'Menjelaskan kode tanpa dieksekusi', 'Mengganti compiler', 'Menghapus bug otomatis', 'Mengenkripsi file'], 'answer_index': 1, 'explanation': 'Komentar diabaikan compiler/interpreter dan membantu dokumentasi.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Debugging adalah proses...', 'options': ['Menulis kode pertama kali', 'Mencari dan memperbaiki error', 'Deploy ke server', 'Desain UI', 'Backup database'], 'answer_index': 1, 'explanation': 'Debugging menelusuri dan memperbaiki bug/defect dalam program.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'IDE (Integrated Development Environment) menyediakan...', 'options': ['Hanya text editor biasa', 'Editor, debugger, dan build tools terintegrasi', 'Router Wi-Fi', 'Antivirus saja', 'Cloud storage saja'], 'answer_index': 1, 'explanation': 'IDE seperti VS Code/Android Studio menggabungkan alat pengembangan.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'API (Application Programming Interface) memungkinkan...', 'options': ['Program berkomunikasi dengan layanan/modul lain', 'Mengganti monitor', 'Mengetik lebih cepat', 'Menyimpan listrik', 'Mematikan OS'], 'answer_index': 0, 'explanation': 'API mendefinisikan cara program memanggil fungsi/layanan eksternal.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Git digunakan terutama untuk...', 'options': ['Editing video', 'Version control kode sumber', 'Menggambar UI', 'Scan virus', 'Routing paket'], 'answer_index': 1, 'explanation': 'Git melacak perubahan kode dan kolaborasi antar developer.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Loop for biasanya dipakai ketika...', 'options': ['Jumlah iterasi sudah diketahui', 'Tidak ada kondisi', 'Hanya satu statement', 'Program selesai', 'Tidak perlu variabel'], 'answer_index': 0, 'explanation': 'For loop cocok saat batas/perulangan sudah jelas (mis. 1..10).'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Switch-case digunakan untuk...', 'options': ['Menyimpan array', 'Memilih aksi berdasarkan nilai diskret', 'Mengompilasi otomatis', 'Menghapus variabel', 'Mengatur jaringan'], 'answer_index': 1, 'explanation': 'Switch membandingkan variabel dengan beberapa case constant.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Konstanta berbeda dari variabel karena...', 'options': ['Nilainya tidak boleh diubah setelah ditetapkan', 'Lebih lambat', 'Hanya untuk teks', 'Tidak punya nama', 'Hanya di Python'], 'answer_index': 0, 'explanation': 'Konstanta (const/final) nilainya fixed selama program berjalan.'},
  {'cat_idx': 2, 'category': 'Pemrograman', 'question': 'Nilai null/nil pada variabel objek berarti...', 'options': ['Objek sedang error fatal', 'Tidak mereferensikan objek apapun', 'Objek paling besar', 'String kosong saja', 'Integer nol'], 'answer_index': 1, 'explanation': 'Null/nil menandakan absence of object reference.'},

  // ── 3: Jaringan Komputer (+12 → total 20) ──
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'LAN (Local Area Network) mencakup area...', 'options': ['Seluruh benua', 'Terbatas seperti gedung/kampus', 'Hanya satelit', 'Deep ocean', 'Antar planet'], 'answer_index': 1, 'explanation': 'LAN menghubungkan perangkat dalam area geografis terbatas.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'WAN (Wide Area Network) biasanya...', 'options': ['Hanya satu ruangan', 'Menghubungkan jaringan jarak jauh/lebih luas', 'Tidak pakai router', 'Hanya Bluetooth', 'Tanpa protokol'], 'answer_index': 1, 'explanation': 'WAN seperti internet menghubungkan jaringan di kota/negara berbeda.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Alamat MAC identifikasi unik perangkat di...', 'options': ['Layer aplikasi saja', 'Layer data link (NIC)', 'Layer presentasi', 'Cloud storage', 'Browser cache'], 'answer_index': 1, 'explanation': 'MAC address melekat pada kartu jaringan perangkat fisik.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Subnet mask digunakan untuk...', 'options': ['Mengenkripsi email', 'Membagi jaringan IP menjadi subnet', 'Mencetak dokumen', 'Mengompilasi kode', 'Scan malware'], 'answer_index': 1, 'explanation': 'Subnet mask menentukan bagian network ID dan host ID dari IP.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Firewall berfungsi untuk...', 'options': ['Mempercepat CPU', 'Menyaring lalu lintas jaringan', 'Menyimpan backup', 'Mengganti DNS', 'Mencetak label'], 'answer_index': 1, 'explanation': 'Firewall menerapkan aturan keamanan pada traffic masuk/keluar.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Perbedaan HTTP dan HTTPS adalah...', 'options': ['HTTPS tidak pakai port', 'HTTPS menambahkan enkripsi TLS/SSL', 'HTTP lebih aman', 'HTTPS hanya untuk email', 'Sama persis'], 'answer_index': 1, 'explanation': 'HTTPS = HTTP + enkripsi, melindungi data in-transit.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'FTP digunakan untuk...', 'options': ['Kirim email', 'Transfer file antar host', 'Resolusi domain', 'Ping test', 'Routing OSPF'], 'answer_index': 1, 'explanation': 'File Transfer Protocol mentransfer file ke/dari server.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'SMTP bertanggung jawab atas...', 'options': ['Browsing web', 'Pengiriman email', 'Streaming video', 'DNS lookup', 'SSH login'], 'answer_index': 1, 'explanation': 'Simple Mail Transfer Protocol mengirim email antar server.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Perintah ping menggunakan protokol...', 'options': ['TCP', 'ICMP', 'FTP', 'SMTP', 'SNMP'], 'answer_index': 1, 'explanation': 'Ping mengirim ICMP echo request untuk uji konektivitas.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'NAT (Network Address Translation) berguna untuk...', 'options': ['Menerjemahkan domain', 'Memetakan IP privat ke IP publik', 'Mengenkripsi disk', 'Sortir paket', 'Compile Java'], 'answer_index': 1, 'explanation': 'NAT memungkinkan banyak perangkat lokal berbagi satu IP publik.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Wi-Fi bekerja pada layer OSI...', 'options': ['Layer 7 saja', 'Layer 1 dan 2 (fisik & data link)', 'Layer 5 saja', 'Tidak masuk OSI', 'Layer 8'], 'answer_index': 1, 'explanation': 'Wi-Fi IEEE 802.11 beroperasi di physical dan data link layer.'},
  {'cat_idx': 3, 'category': 'Jaringan Komputer', 'question': 'Kabel Ethernet umum di jaringan kantor termasuk media...', 'options': ['Nirkabel saja', 'Kabel tembaga twisted pair', 'Satelit', 'Laser medis', 'Ultrasonik'], 'answer_index': 1, 'explanation': 'Ethernet kabel UTP adalah media wired paling umum di LAN.'},

  // ── 4: Keamanan Digital (+12 → total 20) ──
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Antivirus dirancang untuk...', 'options': ['Mempercepat internet', 'Mendeteksi dan mencegah malware', 'Mengganti password Wi-Fi', 'Mengompilasi program', 'Mengatur DHCP'], 'answer_index': 1, 'explanation': 'Antivirus memindai file/proses mencurigakan dan malware known signatures.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Social engineering menyerang...', 'options': ['Hanya firewall', 'Psikologi/manipulasi manusia', 'Kabel fiber', 'Compiler', 'Database index'], 'answer_index': 1, 'explanation': 'Social engineering memanipulasi orang agar memberi akses/info rahasia.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'SSL/TLS pada website berguna untuk...', 'options': ['Memperbesar font', 'Mengenkripsi komunikasi browser-server', 'Menghapus cookie', 'Mengganti DNS', 'Mempercepat CPU'], 'answer_index': 1, 'explanation': 'TLS melindungi data sensitif (login, kartu kredit) saat transit.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Serangan brute force mencoba...', 'options': ['Satu password saja', 'Semua kombinasi password/kunci', 'Mematikan listrik', 'Mengganti MAC', 'Format hard disk otomatis'], 'answer_index': 1, 'explanation': 'Brute force mencoba kombinasi secara exhaustive sampai berhasil.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Man-in-the-Middle (MitM) terjadi ketika...', 'options': ['Server mati', 'Penyerang menyadap/mengubah komunikasi di tengah', 'Password terlalu panjang', 'Backup gagal', 'Antivirus update'], 'answer_index': 1, 'explanation': 'MitM: attacker berada di antara dua pihak yang berkomunikasi.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'SQL Injection mengeksploitasi...', 'options': ['Input yang tidak divalidasi pada query database', 'Monitor retak', 'Kabel putus', 'Font CSS', 'Baterai laptop'], 'answer_index': 0, 'explanation': 'Input jahat dimasukkan ke query SQL sehingga database dieksploitasi.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Cross-Site Scripting (XSS) menempatkan...', 'options': ['Virus di hardware', 'Script berbahaya di halaman web', 'Kabel tambahan', 'Firewall mati', 'DNS record A'], 'answer_index': 1, 'explanation': 'XSS menyisipkan script jahat yang dijalankan browser korban.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Backup data rutin penting untuk...', 'options': ['Mempercepat CPU', 'Pemulihan setelah kehilangan data', 'Mengganti router', 'Menghapus malware otomatis', 'Meningkatkan FPS game'], 'answer_index': 1, 'explanation': 'Backup memungkinkan restore jika ransomware, human error, atau bencana.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Password yang kuat biasanya...', 'options': ['Nama tanggal lahir', 'Panjang, acak, kombinasi karakter', 'Satu huruf saja', 'Sama dengan username', 'Kosong'], 'answer_index': 1, 'explanation': 'Password kuat: panjang, acak, campuran huruf/angka/simbol.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Keylogger adalah malware yang...', 'options': ['Mencatat penekanan tombol keyboard', 'Mempercepat RAM', 'Mengganti wallpaper', 'Update OS', 'Scan port saja'], 'answer_index': 0, 'explanation': 'Keylogger merekam input keyboard untuk mencuri kredensial.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Prinsip least privilege berarti user diberi...', 'options': ['Semua akses admin', 'Hanya hak minimum yang dibutuhkan', 'Akses tanpa password', 'Root selamanya', 'Token publik'], 'answer_index': 1, 'explanation': 'Least privilege mengurangi risiko jika akun disusupi.'},
  {'cat_idx': 4, 'category': 'Keamanan Digital', 'question': 'Phishing via SMS sering disebut...', 'options': ['Vishing', 'Smishing', 'DDoS', 'Hashing', 'Ping flood'], 'answer_index': 1, 'explanation': 'Smishing = SMS + phishing, menipu via pesan teks.'},
];
